"""123123

Revision ID: 4d73af70b817
Revises: 
Create Date: 2020-09-14 16:16:50.531170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d73af70b817'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lanmu_id', sa.INTEGER(), nullable=True),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('article_yuedu', sa.String(length=100), nullable=False),
    sa.Column('article_time', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['lanmu_id'], ['lanmu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
