"""empty message

Revision ID: 9a9bc20c40ff
Revises: 
Create Date: 2020-08-05 14:51:40.392427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9bc20c40ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('lanmu', sa.Column('lanmu_desc', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lanmu', 'lanmu_desc')
    op.drop_column('article', 'description')
    # ### end Alembic commands ###
